apiVersion: v1
kind: Namespace
metadata:
  name: mern-chatapp-prod
  labels:
    app.kubernetes.io/name: mern-chatapp
    app.kubernetes.io/environment: prod
    pod-security.kubernetes.io/enforce: restricted
