apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-chatapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GeoAziz/chat-platform-k8s
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-chatapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GeoAziz/chat-platform-k8s
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
