apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-chatapp-prod
  namespace: argocd
spec:
  project: mern-chatapp
  source:
    repoURL: https://github.com/your-username/Mern_ChatApp.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: mern-chatapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
