apiVersion: v1
kind: Namespace
metadata:
  name: mern-chatapp-dev
  labels:
    app.kubernetes.io/name: mern-chatapp
    app.kubernetes.io/environment: dev
    pod-security.kubernetes.io/enforce: baseline
